site_name: Developer Notes
site_url: https://emptycuphq.github.io/notes/
repo_url: https://github.com/emptycuphq/notes
repo_name: emptycuphq/notes
edit_uri: ""            # Disable edit button for pages after github integration


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github

  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode

nav:
  - Home:
    - Getting started: 'index.md'
    - Getting stuck: 'stuck.md'
    - Guidelines: 'guidelines.md'
    - Contributors: 'contributors.md'
    - Etiquette: 'etiquette.md'
    - Inspiration: 'inspiration.md'
    - Vision: 'vision.md'

  - Basics:
    - Overview: 'basics.md'
    - Operating System:
      - Installation: 'os/install.md'
      - Filesystem: 'os/filesystem.md'
      - Users: 'os/users.md'
      - Software packages: 'os/packages.md'
    - Command Line:
      - Essentials: 'cli/essentials.md'
      - Useful: 'cli/useful.md'
      - Remote: 'cli/remote.md'
      - Shell operators: 'cli/operators.md'
    - Git:
      - Workflow: 'git/workflow.md'
      - Github: 'git/github.md'
      - Commands: 'git/commands.md'
      - Branches: 'git/branches.md'

    - Others:
      - Markdown: 'basics/markdown.md'
      - mkdocs: 'basics/mkdocs.md'

  - Frontend: 'frontend.md'
  - Backend: 'backend.md'
  - Scripting: 'scripting.md'
  - Deployment: 'deployment.md'
  - Code: 'code.md'
  - Concepts: 'concepts.md'